
// This file is automatically generated. Do not edit it directly.
import { createClient, RealtimeChannel, REALTIME_SUBSCRIBE_STATES } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xazssvfcifagxbibnxqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhenNzdmZjaWZhZ3hiaWJueHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Mzg1OTQsImV4cCI6MjA1ODExNDU5NH0.uQhGXlOuFEY3-2NJXMUeuyElqeIFnElKX7PWTIZ3hcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Export REALTIME_SUBSCRIBE_STATES
export { REALTIME_SUBSCRIBE_STATES };

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
